#!/bin/sh

echo "Glacier Package Manager"
echo "====================================================================="
echo "An extremely light and fast ackage manager written entirely in shell."
echo ""
echo "glacier-install - Install a program"
echo "glacier-update - Update a program"
echo "glacier-remove - Remove a program"
echo "glacier-query - Query a program"
echo ""
echo "IMPORTANT REMINDER - Glacier is unlike a traditional package manager where you apend a package name to the command. Instead, Glacier will ask you which package you wish to install."
echo ""
echo "Copyright (c) 2022 Everest Linux Developers"
echo "This software includes no warranty whatsoever. See the GNU GPL v3.0 for more information."
