#!/bin/sh

echo "Glacier Package Manager v1.0"
echo "====================================================================="
echo "An extremely light and fast ackage manager written entirely in shell."
echo ""
echo "glacier-install - Install a package"
echo "glacier-update - Update a package"
echo "glacier-remove - Remove a package"
echo "glacier-query - Query a package"
echo "glacier-cache - Add a package to the cache"
echo "glacier-cache-install - Install a cached package"
echo "glacier-cache-clear - Clear Glacier's cache"
echo ""
echo "IMPORTANT REMINDER - Glacier will ask you which package to install, glacier-install <package> will not work."
echo ""
echo "Glacier - Copyright (C) 2022  Everest Linux"
echo "This program comes with ABSOLUTELY NO WARRANTY; for details see section 15 of the GNU GPL v3."
echo "This is free software, and you are welcome to redistribute it"
echo "under certain conditions; type `show c' for details."
